// LIGHT
module.exports = {
  PRIMARY_LIGHT: "#FFFFFF",
  PRIMARY_TEXT_LIGHT: "#222222",
  SECONDARY_TEXT_LIGHT: "#6A6666",
  PRIMARY_ACCENT_LIGHT: "#4B96FF",
  PRIMARY_BG_LIGHT: "#EBECF1",
  // DARK
  PRIMARY_DARK: "#141621",
  PRIMARY_TEXT_DARK: "#FFFFFF",
  SECONDARY_TEXT_DARK: "#FFFFFF",
  PRIMARY_ACCENT_DARK: "#4B96FF",
  PRIMARY_BG_DARK: "#141621",

  LIGHT_GRAY: "#B3B9C5",

  ACCENT_LOW_OPA: "rgba(106, 39, 159, 0.5)",
};
